name: Build CMS-NodeJS Image
run-name: Build CMS-NodeJS Image for version ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-?**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag counselkit/cms-nodejs:${{ github.ref_name }} --tag counselkit/cms-nodejs:latest
      - name: Push the docker image
        run: |
          docker login --username counselkit --password ${{ secrets.DOCKER_TOKEN }}
          docker push counselkit/cms-nodejs:latest
          docker push counselkit/cms-nodejs:${{ github.ref_name }}
        
